= Hello World with Docker and Kubernetes

This repo consists of a Spring Boot Hello World application. It shows:

. Run & test the application from CLI
. Create a Docker image, run the container and test it
. Create Kubernetes deployment and ingress

Let's get started!

== CLI

=== Run App

```
mvn spring-boot:run
```

=== Test Application

```
curl http://localhost:8080
```

== Docker

=== Build Application

```
mvn clean package
```

=== Build Docker Image

```
docker image build -t 190743/hello-world:latest .
```

=== Push Docker Image

```
docker image push 190743/hello-world:latest
```

=== Run Docker Container

```
docker container run -d --name hello-world -p 8080:8080 190743/hello-world:latest
```

=== Test Application

```
curl http://localhost:8080
```

=== Delete Docker Container

```
docker container rm -f hello-world
```
=== Install Kubernetes
```
Install choco for windows with powershell = Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
choco install kubernetes-cli
=== Install Minikube
```
Install choco for windows with powershell = Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
choco install minikube
minikube start
minikube dashboard 
```


=== Create Deployment

```
kubectl apply -f deployment.yaml
```
=== Create Service
```
kubectl apply -f service.yaml
```
=== Create Ingress
```
kubectl apply -f ingress.yaml
```
=== Build for local
```
use kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.1.2/deploy/static/provider/cloud/deploy.yaml

```
=== Delete Deployment

```
kubectl delete -f deployment.yaml
```
=== Deploy Heroku
```
https://hello-app-430.herokuapp.com/
```
